name: example
description: A sample command-line application as an example for kiwi.
version: 0.1.0
author: Romain Rastel <lets4r@gmail.com>
homepage: https://github.com/letsar/kiwi

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  sunny_kiwi: ^1.0.1-nullsafety.0

dependency_overrides:
  sunny_kiwi:
    path: ../kiwi
  sunny_kiwi_generator:
    path: ../kiwi_generator
dev_dependencies:
  test: ^1.16.8
  build_runner: ^1.12.2
  kiwi_generator: ^2.1.1
