name: kiwi_generator
description: Generates dependency injection code using the kiwi package to reduce development time.
#version: 0.4.0
author: Romain Rastel <lets4r@gmail.com>
homepage: https://github.com/letsar/kiwi
publish_to: none

environment:
  sdk: '>=2.9.0 <3.0.0'

dependencies:  
  analyzer: ^0.41.1
  build: ^1.5.2
  build_config: ^0.4.4
  code_builder: ^3.5.0
  dart_style: ^1.3.10
  kiwi:
    git:
      url: https://github.com/SunnyApp/kiwi.git
      ref: master
      path: kiwi
  path: any
  source_gen: ^0.9.9

  # analyzer: <0.39.0
  # build: ">=1.0.0 <1.2.0"
  # build_config: ^0.4.1+1
  # code_builder: ^3.2.0
  # dart_style: ^1.2.9
  # kiwi:
  #   git:
  #     url: https://github.com/SunnyApp/kiwi.git
  #     ref: master
  #     path: kiwi
  # path: ^1.6.4
  # source_gen: ^0.9.2

dev_dependencies:
  build_runner: ^1.10.7
  build_test: ^1.3.0
  test: ^1.15.7

