name: sunny_kiwi
description: A fork of the simple yet efficient IoC container for Dart and Flutter (can be coupled with the kiwi_generator package).
version: 0.3.0-nullsafety.0
author: Romain Rastel <lets4r@gmail.com>
homepage: https://github.com/letsar/kiwi

dependencies:
  logging: ^1.0.0
  uuid: ^3.0.1
  collection: ^1.15.0-nullsafety.4

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  test: ^1.16.8
